version: '3'

services:

  api:
    image: oierarribas/api-mangaweb2
    container_name: api-container
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: ./django-start.sh
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/secproductos`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

  web:
    image: oierarribas/front-mangaweb2
    container_name: front-container
    ports:
      - 5001:80
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  db:
    image: postgres
    container_name: db-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: oier121314
      POSTGRES_PASSWORD: oier213141
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"

  traefik:
    image: "traefik:v2.5"
    container_name: traefik-container
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"







