version: '3'

services:

  api:
    image: oierarribas/api-mangaweb
    container_name: api-container
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: ./django-start.sh
    depends_on:
      - db

  web:
    image: oierarribas/front-mangaweb2
    container_name: front-container
    ports:
      - 80:80
    depends_on:
      - api

  db:
    image: postgres
    container_name: db-container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
